/* SF Bay Nautical Chart — PWA */

(async () => {
  // Load bounds generated by scripts/write_manifest.py
  const bounds = await fetch('bounds.json').then(r => r.json());

  const map = L.map('map', {
    center: [(bounds.north + bounds.south) / 2, (bounds.west + bounds.east) / 2],
    zoom: 10,
    zoomControl: false,
    attributionControl: false,
  });

  // Raster chart tile layer
  L.tileLayer(`tiles/{z}/{x}/{y}.${bounds.tileExtension}`, {
    minZoom: bounds.minZoom,
    maxZoom: 20,
    maxNativeZoom: bounds.maxZoom,
    // Tiles are 512px images declared as tileSize:256 so the browser
    // renders them at 2× CSS density → pixel-perfect on Retina screens.
    tileSize: 256,
    // Clamp panning to chart bounds (with some padding)
    bounds: L.latLngBounds(
      [bounds.south - 0.1, bounds.west - 0.1],
      [bounds.north + 0.1, bounds.east + 0.1]
    ),
    keepBuffer: 2,
    // Smooth transitions on zoom
    updateWhenZooming: false,
    errorTileUrl: '', // blank on missing tile (ocean outside chart)
  }).addTo(map);

  // Attribution — show active SW cache version so it's easy to verify updates
  const cacheKeys = await caches.keys();
  const shellKey = cacheKeys.find(k => k.startsWith('shell-'));
  const cacheVersion = shellKey ? shellKey.replace('shell-', '') : 'uncached';
  L.control.attribution({ prefix: false, position: 'bottomleft' })
    .addAttribution(`NOAA Chart 18649 · ${cacheVersion}`)
    .addTo(map);

  // ── GPS / Location ───────────────────────────────────────────────────────
  let locationMarker = null;
  let accuracyCircle = null;
  let trackingEnabled = false;
  let firstFix = true;

  const statusEl = document.getElementById('status');
  const locateBtn = document.getElementById('locate-btn');

  function showStatus(msg, autoHide = false) {
    statusEl.textContent = msg;
    statusEl.classList.remove('hidden');
    if (autoHide) {
      setTimeout(() => statusEl.classList.add('hidden'), 3000);
    }
  }

  function onLocationFound(e) {
    const { latlng, accuracy } = e;

    // Position dot
    if (!locationMarker) {
      locationMarker = L.circleMarker(latlng, {
        radius: 8,
        color: '#fff',
        weight: 2,
        fillColor: '#4a90d9',
        fillOpacity: 1,
      }).addTo(map);
    } else {
      locationMarker.setLatLng(latlng);
    }

    // Accuracy circle
    if (!accuracyCircle) {
      accuracyCircle = L.circle(latlng, {
        radius: accuracy,
        className: 'gps-accuracy',
      }).addTo(map);
    } else {
      accuracyCircle.setLatLng(latlng);
      accuracyCircle.setRadius(accuracy);
    }

    // Auto-center on first fix
    if (firstFix) {
      map.setView(latlng, Math.max(map.getZoom(), 12));
      firstFix = false;
    }

    showStatus(`GPS ±${Math.round(accuracy)}m`, true);
  }

  function onLocationError(e) {
    showStatus(e.message.includes('denied')
      ? 'Location access denied — enable in Settings'
      : `GPS error: ${e.message}`
    );
    trackingEnabled = false;
    locateBtn.classList.remove('active');
  }

  map.on('locationfound', onLocationFound);
  map.on('locationerror', onLocationError);

  locateBtn.addEventListener('click', () => {
    if (!trackingEnabled) {
      trackingEnabled = true;
      firstFix = true;
      locateBtn.classList.add('active');
      showStatus('Acquiring GPS…');
      map.locate({ watch: true, enableHighAccuracy: true, timeout: 15000 });
    } else {
      // Tap again: re-center on current position
      if (locationMarker) {
        map.setView(locationMarker.getLatLng(), map.getZoom());
      }
    }
  });

  // ── Zoom controls (custom position for iPhone) ───────────────────────────
  L.control.zoom({ position: 'bottomright' }).addTo(map);

  // ── Offline download button ───────────────────────────────────────────────
  const offlineBtn = document.getElementById('offline-btn');

  async function checkOfflineReady() {
    const tileKey = (await caches.keys()).find(k => k.startsWith('tiles-'));
    if (!tileKey) return;
    const tileCache = await caches.open(tileKey);
    const keys = await tileCache.keys();
    if (keys.length > 0) offlineBtn.classList.add('done');
  }

  offlineBtn.addEventListener('click', async () => {
    if (offlineBtn.classList.contains('done')) {
      showStatus('Chart already cached for offline use', true);
      return;
    }
    showStatus('Downloading chart…');
    offlineBtn.disabled = true;
    try {
      const manifest = await fetch('tile-manifest.json').then(r => r.json());
      const tileKey = (await caches.keys()).find(k => k.startsWith('tiles-')) || 'tiles-v6';
      const tileCache = await caches.open(tileKey);
      const CHUNK = 20;
      let done = 0;
      for (let i = 0; i < manifest.length; i += CHUNK) {
        const chunk = manifest.slice(i, i + CHUNK);
        await Promise.allSettled(chunk.map(p => tileCache.add(p)));
        done += chunk.length;
        showStatus(`Downloading… ${Math.round(done / manifest.length * 100)}%`);
      }
      offlineBtn.classList.add('done');
      showStatus('Chart cached for offline use', true);
    } catch (e) {
      showStatus('Download failed — check connection');
    } finally {
      offlineBtn.disabled = false;
    }
  });

  checkOfflineReady();

  // ── Service Worker registration ──────────────────────────────────────────
  if ('serviceWorker' in navigator) {
    try {
      const reg = await navigator.serviceWorker.register('sw.js');
      reg.addEventListener('updatefound', () => {
        showStatus('Chart update available — reload to apply');
      });
    } catch (e) {
      console.warn('SW registration failed:', e);
    }
  }

  showStatus('Chart ready', true);
})();
