/* SF Bay Nautical Chart — PWA */

(async () => {
  // Load bounds generated by scripts/write_manifest.py
  const bounds = await fetch('bounds.json').then(r => r.json());

  const map = L.map('map', {
    center: [(bounds.north + bounds.south) / 2, (bounds.west + bounds.east) / 2],
    zoom: 11,
    zoomControl: false,
    attributionControl: false,
  });

  // Raster chart tile layer
  L.tileLayer(`tiles/{z}/{x}/{y}.${bounds.tileExtension}`, {
    minZoom: bounds.minZoom + 1,
    maxZoom: bounds.maxZoom + 1,
    maxNativeZoom: bounds.maxZoom + 1,
    tileSize: 512,
    zoomOffset: -1,
    // Clamp panning to chart bounds (with some padding)
    bounds: L.latLngBounds(
      [bounds.south - 0.1, bounds.west - 0.1],
      [bounds.north + 0.1, bounds.east + 0.1]
    ),
    keepBuffer: 2,
    // Smooth transitions on zoom
    updateWhenZooming: false,
    errorTileUrl: '', // blank on missing tile (ocean outside chart)
  }).addTo(map);

  // Attribution (small, unobtrusive)
  L.control.attribution({ prefix: false, position: 'bottomleft' })
    .addAttribution('NOAA Chart 18649')
    .addTo(map);

  // ── GPS / Location ───────────────────────────────────────────────────────
  let locationMarker = null;
  let accuracyCircle = null;
  let trackingEnabled = false;
  let firstFix = true;

  const statusEl = document.getElementById('status');
  const locateBtn = document.getElementById('locate-btn');

  function showStatus(msg, autoHide = false) {
    statusEl.textContent = msg;
    statusEl.classList.remove('hidden');
    if (autoHide) {
      setTimeout(() => statusEl.classList.add('hidden'), 3000);
    }
  }

  function onLocationFound(e) {
    const { latlng, accuracy } = e;

    // Position dot
    if (!locationMarker) {
      locationMarker = L.circleMarker(latlng, {
        radius: 8,
        color: '#fff',
        weight: 2,
        fillColor: '#4a90d9',
        fillOpacity: 1,
      }).addTo(map);
    } else {
      locationMarker.setLatLng(latlng);
    }

    // Accuracy circle
    if (!accuracyCircle) {
      accuracyCircle = L.circle(latlng, {
        radius: accuracy,
        className: 'gps-accuracy',
      }).addTo(map);
    } else {
      accuracyCircle.setLatLng(latlng);
      accuracyCircle.setRadius(accuracy);
    }

    // Auto-center on first fix
    if (firstFix) {
      map.setView(latlng, Math.max(map.getZoom(), 13));
      firstFix = false;
    }

    showStatus(`GPS ±${Math.round(accuracy)}m`, true);
  }

  function onLocationError(e) {
    showStatus(e.message.includes('denied')
      ? 'Location access denied — enable in Settings'
      : `GPS error: ${e.message}`
    );
    trackingEnabled = false;
    locateBtn.classList.remove('active');
  }

  map.on('locationfound', onLocationFound);
  map.on('locationerror', onLocationError);

  locateBtn.addEventListener('click', () => {
    if (!trackingEnabled) {
      trackingEnabled = true;
      firstFix = true;
      locateBtn.classList.add('active');
      showStatus('Acquiring GPS…');
      map.locate({ watch: true, enableHighAccuracy: true, timeout: 15000 });
    } else {
      // Tap again: re-center on current position
      if (locationMarker) {
        map.setView(locationMarker.getLatLng(), map.getZoom());
      }
    }
  });

  // ── Zoom controls (custom position for iPhone) ───────────────────────────
  L.control.zoom({ position: 'bottomright' }).addTo(map);

  // ── Service Worker registration ──────────────────────────────────────────
  if ('serviceWorker' in navigator) {
    try {
      const reg = await navigator.serviceWorker.register('sw.js');
      reg.addEventListener('updatefound', () => {
        showStatus('Chart update available — reload to apply');
      });
    } catch (e) {
      console.warn('SW registration failed:', e);
    }
  }

  showStatus('Chart ready', true);
})();
